name: Combined Workflows

on:
  schedule:
    - cron: '0 0 * * 0'  # Uruchamia się o północy (UTC) w niedzielę
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-and-build:
    runs-on: ubuntu-latest  # Ustawienie domyślnego serwera Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.1'

    - name: Use Bash shell
      shell: bash
      run: |
        # Uruchomienie skryptu installResources.sh znajdującego się w repozytorium
        ./installResources.sh

    - name: Build executable
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: build/*.exe
